In [1]:
import numpy
a=numpy.zeros([3,2])

In [1]:
import matplotlib.pyplot
%matplotlib inline
a[0,0]=1
a[0,1]=2
a[1,0]=3
a[2,1]=4
matplotlib.pyplot.imshow(a,interpolation='nearest')

NameError: name 'a' is not defined

In [32]:
class neuralNetwork:
    def __init__(self,inputnodes,hiddennodes,outputnodes,learningrate):
        self.inodes=inputnodes
        self.hnodes=hiddennodes
        self.onodes=outputnodes
        self.lr=learningrate
#         self.wih=(numpy.random.rand(self.hnodes,self.inodes)-0.5)
#         self.who=(numpy.random.rand(self.onodes,self.hnodes)-0.5)
        self.wih=numpy.random.normal(0.0,pow(self.hnodes,-0.5),(self.hnodes,self.inodes))
        self.who=numpy.random.normal(0.0,pow(self.onodes,-0.5),(self.onodes,self.hnodes))
        self.activation_function=lambda x: scipy.special.expit(x)
    def train(self,inputs_list,targets_list):
        inputs=numpy.array(inputs_list,ndmin=2).T
        targets=numpy.array(targets_list,ndmin=2).T
        hidden_inputs=numpy.dot(self.wih,inputs)
        
        hidden_outputs=self.activation_function(hidden_inputs)
        
        final_inputs=numpy.dot(self.who,hidden_outputs)
        
        final_outputs=self.activation_function(final_inputs)
        
        output_errors=targets-final_outputs
        hidden_errors=numpy.dot(self.who.T,output_errors)
        self.who += self.lr * numpy.dot((output_errors *
            final_outputs * (1.0 - final_outputs)),
            numpy.transpose(hidden_outputs))
        self.wih += self.lr * numpy.dot((hidden_errors *
            hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        
    def query(self,inputs_list):
        inputs=numpy.array(inputs_list,ndmin=2).T
        hidden_inputs=numpy.dot(self.wih,inputs)
        hidden_outputs=self.activation_function(hidden_inputs)
        final_inputs=numpy.dot(self.who,hidden_outputs)
        final_outputs=self.activation_function(final_inputs)
        return final_outputs
        

In [47]:
import scipy.special
input_nodes=3
hidden_nodes=3
output_nodes=3
learning_rate=0.3
n=neuralNetwork(input_nodes,hidden_nodes,output_nodes,learning_rate)
n.query([1,0.5,-1.5])

array([[0.46070796],
       [0.60538895],
       [0.35349115]])

In [44]:
import numpy
numpy.random.rand(3,3)-0.5

array([[-0.07294177, -0.32538313, -0.38885802],
       [-0.37395795, -0.43007241,  0.02090096],
       [ 0.2130113 , -0.48398364,  0.28896031]])

In [45]:
numpy.random.normal(0.0,pow(3,-0.5),(3,3))

array([[ 0.56385668,  0.00697191,  0.20408502],
       [-0.37916886,  0.17826345,  0.5027339 ],
       [-0.76128339,  0.36540762,  0.40924877]])

In [36]:
import scipy.special
scipy.special.expit([[1],[2],[3]])

array([[0.73105858],
       [0.88079708],
       [0.95257413]])